module.exports = {
  accessoryUpgrades: {
    WOLF_TALISMAN: [
      'WOLF_RING',
    ],
    RING_POTION_AFFINITY: [
      'ARTIFACT_POTION_AFFINITY',
    ],
    POTION_AFFINITY_TALISMAN: [
      'RING_POTION_AFFINITY',
      'ARTIFACT_POTION_AFFINITY',
    ],
    FEATHER_RING: [
      'FEATHER_ARTIFACT',
    ],
    FEATHER_TALISMAN: [
      'FEATHER_RING',
      'FEATHER_ARTIFACT',
    ],
    SEA_CREATURE_RING: [
      'SEA_CREATURE_ARTIFACT',
    ],
    SEA_CREATURE_TALISMAN: [
      'SEA_CREATURE_RING',
      'SEA_CREATURE_ARTIFACT',
    ],
    HEALING_TALISMAN: [
      'HEALING_RING',
    ],
    CANDY_ARTIFACT: [
      'CANDY_RELIC',
    ],
    CANDY_RING: [
      'CANDY_ARTIFACT',
      'CANDY_RELIC',
    ],
    CANDY_TALISMAN: [
      'CANDY_RING',
      'CANDY_ARTIFACT',
      'CANDY_RELIC',
    ],
    INTIMIDATION_RING: [
      'INTIMIDATION_ARTIFACT',
    ],
    INTIMIDATION_TALISMAN: [
      'INTIMIDATION_RING',
      'INTIMIDATION_ARTIFACT',
    ],
    SPIDER_RING: [
      'SPIDER_ARTIFACT',
    ],
    SPIDER_TALISMAN: [
      'SPIDER_RING',
      'SPIDER_ARTIFACT',
    ],
    RED_CLAW_RING: [
      'RED_CLAW_ARTIFACT',
    ],
    RED_CLAW_TALISMAN: [
      'RED_CLAW_RING',
      'RED_CLAW_ARTIFACT',
    ],
    HUNTER_TALISMAN: [
      'HUNTER_RING',
    ],
    ZOMBIE_RING: [
      'ZOMBIE_ARTIFACT',
    ],
    ZOMBIE_TALISMAN: [
      'ZOMBIE_RING',
      'ZOMBIE_ARTIFACT',
    ],
    BAT_RING: [
      'BAT_ARTIFACT',
    ],
    BAT_TALISMAN: [
      'BAT_RING',
      'BAT_ARTIFACT',
    ],
    BROKEN_PIGGY_BANK: [
      'CRACKED_PIGGY_BANK',
      'PIGGY_BANK',
    ],
    CRACKED_PIGGY_BANK: [
      'PIGGY_BANK',
    ],
    SPEED_TALISMAN: [
      'SPEED_RING',
      'SPEED_ARTIFACT',
    ],
    SPEED_RING: [
      'SPEED_ARTIFACT',
    ],
    PERSONAL_COMPACTOR_4000: [
      'PERSONAL_COMPACTOR_5000',
      'PERSONAL_COMPACTOR_6000',
      'PERSONAL_COMPACTOR_7000',
    ],
    PERSONAL_COMPACTOR_5000: [
      'PERSONAL_COMPACTOR_6000',
      'PERSONAL_COMPACTOR_7000',
    ],
    PERSONAL_COMPACTOR_6000: [
      'PERSONAL_COMPACTOR_7000',
    ],
    SCARF_STUDIES: [
      'SCARF_THESIS',
      'SCARF_GRIMOIRE',
    ],
    SCARF_THESIS: [
      'SCARF_GRIMOIRE',
    ],
    CAT_TALISMAN: [
      'LYNX_TALISMAN',
      'CHEETAH_TALISMAN',
    ],
    LYNX_TALISMAN: [
      'CHEETAH_TALISMAN',
    ],
    SHADY_RING: [
      'CROOKED_ARTIFACT',
      'SEAL_OF_THE_FAMILY',
    ],
    CROOKED_ARTIFACT: [
      'SEAL_OF_THE_FAMILY',
    ],
    TREASURE_TALISMAN: [
      'TREASURE_RING',
      'TREASURE_ARTIFACT',
    ],
    TREASURE_RING: [
      'TREASURE_ARTIFACT',
    ],
    BEASTMASTER_CREST_COMMON: [
      'BEASTMASTER_CREST_UNCOMMON',
      'BEASTMASTER_CREST_RARE',
      'BEASTMASTER_CREST_EPIC',
      'BEASTMASTER_CREST_LEGENDARY',
    ],
    BEASTMASTER_CREST_UNCOMMON: [
      'BEASTMASTER_CREST_RARE',
      'BEASTMASTER_CREST_EPIC',
      'BEASTMASTER_CREST_LEGENDARY',
    ],
    BEASTMASTER_CREST_RARE: [
      'BEASTMASTER_CREST_EPIC',
      'BEASTMASTER_CREST_LEGENDARY',
    ],
    BEASTMASTER_CREST_EPIC: [
      'BEASTMASTER_CREST_LEGENDARY',
    ],
    RAGGEDY_SHARK_TOOTH_NECKLACE: [
      'DULL_SHARK_TOOTH_NECKLACE',
      'HONED_SHARK_TOOTH_NECKLACE',
      'SHARP_SHARK_TOOTH_NECKLACE',
      'RAZOR_SHARP_SHARK_TOOTH_NECKLACE',
    ],
    DULL_SHARK_TOOTH_NECKLACE: [
      'HONED_SHARK_TOOTH_NECKLACE',
      'SHARP_SHARK_TOOTH_NECKLACE',
      'RAZOR_SHARP_SHARK_TOOTH_NECKLACE',
    ],
    HONED_SHARK_TOOTH_NECKLACE: [
      'SHARP_SHARK_TOOTH_NECKLACE',
      'RAZOR_SHARP_SHARK_TOOTH_NECKLACE',
    ],
    SHARP_SHARK_TOOTH_NECKLACE: [
      'RAZOR_SHARP_SHARK_TOOTH_NECKLACE',
    ],
    BAT_PERSON_TALISMAN: [
      'BAT_PERSON_RING',
      'BAT_PERSON_ARTIFACT',
    ],
    BAT_PERSON_RING: [
      'BAT_PERSON_ARTIFACT',
    ],
    LUCKY_HOOF: [
      'ETERNAL_HOOF',
    ],
    WITHER_ARTIFACT: [
      'WITHER_RELIC',
    ],
    WEDDING_RING_0: [
      'WEDDING_RING_2',
      'WEDDING_RING_4',
      'WEDDING_RING_7',
      'WEDDING_RING_9',
    ],
    WEDDING_RING_2: [
      'WEDDING_RING_4',
      'WEDDING_RING_7',
      'WEDDING_RING_9',
    ],
    WEDDING_RING_4: [
      'WEDDING_RING_7',
      'WEDDING_RING_9',
    ],
    WEDDING_RING_7: [
      'WEDDING_RING_9',
    ],
    CAMPFIRE_TALISMAN_1: [
      'CAMPFIRE_TALISMAN_4',
      'CAMPFIRE_TALISMAN_8',
      'CAMPFIRE_TALISMAN_13',
      'CAMPFIRE_TALISMAN_21',
    ],
    CAMPFIRE_TALISMAN_4: [
      'CAMPFIRE_TALISMAN_8',
      'CAMPFIRE_TALISMAN_13',
      'CAMPFIRE_TALISMAN_21',
    ],
    CAMPFIRE_TALISMAN_8: [
      'CAMPFIRE_TALISMAN_13',
      'CAMPFIRE_TALISMAN_21',
    ],
    CAMPFIRE_TALISMAN_13: [
      'CAMPFIRE_TALISMAN_21',
    ],
    JERRY_TALISMAN_GREEN: [
      'JERRY_TALISMAN_BLUE',
      'JERRY_TALISMAN_PURPLE',
      'JERRY_TALISMAN_GOLDEN',
    ],
    JERRY_TALISMAN_BLUE: [
      'JERRY_TALISMAN_PURPLE',
      'JERRY_TALISMAN_GOLDEN',
    ],
    JERRY_TALISMAN_PURPLE: [
      'JERRY_TALISMAN_GOLDEN',
    ],
  },
};
